name: bsdsba2028-dmw-2301
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.12
  - ipykernel
  - scikit-learn
  - pip
  - scipy
  - beautifulsoup4
  - pip:
    - jupyter-contrib-nbextensions
    - ipywidgets
    - openpyxl
