name: bsdsba2028-dmw-2301
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.10.8
  - numpy=2.4.1
  - pandas=2.3.3
  - python=3.12.12
  - ipykernel=7.1.0
  - scikit-learn=1.8.0
  - pip=25.3
  - scipy=1.17.0
  - beautifulsoup4=4.14.3
  - pip:
    - jupyter-contrib-nbextensions==0.6.4
    - ipywidgets==8.1.8
    - openpyxl==3.1.5
